@startuml

actor "Aluno" as Aluno
actor "Professor" as Professor
actor "Empresa Parceira" as Empresa

usecase "Cadastrar-se no Sistema" as UC1
usecase "Consultar Extrato" as UC2
usecase "Trocar Moedas por Vantagens" as UC4
usecase "Cadastrar Vantagem" as UC5
usecase "Enviar Moedas" as UC6
usecase "Notificar por Email" as UC7

Aluno --> UC1
Aluno --> UC2
Aluno --> UC4

Professor --> UC2
Professor --> UC6

Empresa --> UC5

UC6 ..> UC7 : <<extend>>
UC4 ..> UC7 : <<extend>>

@enduml
